# Generated by Django 4.1.2 on 2022-10-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
