# Generated by Django 4.1.2 on 2022-10-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_post_author_alter_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
